hotword_detector:
  model: 'resources/snowboy/snowboy.umdl'
  sensitivity: 0.6

recorder:
  vad: wavelet
  bg_noise_samples: 20

services:
  -
    type: pocketsphinx
    confidence_strategy: default
    verbose: false
    buffer_size: 1024
    decoder:
      '-hmm': 'resources/pocketsphinx/model/ru-ru/cmu_ru-ru'
      '-lm': 'resources/pocketsphinx/model/ru-ru/robot.lm.bin'
      '-dict': 'resources/pocketsphinx/model/ru-ru/robot.dic'
    local: true

  -
    type: google
    language_code: ru-RU
