hotword_detector:
  service_name: snowboy
  model: 'resources/snowboy/jarvis.pmdl'
  sensitivity: 0.5

recorder:
  vad: wavelet
  bg_noise_samples: 20
  sensitivity: 1.0
  verbose: true

services:
  -
    service_name: pocketsphinx
    confidence_strategy: default
    verbose: false
    buffer_size: 1024
    decoder:
      '-hmm': 'resources/pocketsphinx/model/ru-ru/cmu_ru-ru'
      '-lm': 'resources/pocketsphinx/model/ru-ru/robot2.lm.bin'
      '-dict': 'resources/pocketsphinx/model/ru-ru/robot2.dic'
    local: true

  -
    service_name: google
    language_code: ru-RU
    # Not implemented yet.
    known_alternatives: ''
    filter_unknown: false

handler_behaviour:
  confidence_threshold: 0.2
